@BankRUs.Api_HostAddress = https://localhost:8000

### Öppna konto

POST https://localhost:8000/api/accounts
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Doe",
  "socialSecurityNumber": "19900101-2013",
  "email": "jane@doe.com"
}
### Open Account

POST https://localhost:8000/api/accounts
Content-Type: application/json

{
  "firstName": "Jaaa",
  "lastName": "Doooo",
  "socialSecurityNumber": "202612312385",
  "email": "jaaa@doe.com"
}

### Open Bank Account

POST https://localhost:8000/api/bank-accounts
Content-Type: application/json

{
  "userId": "da2e7d2e-c2ff-4de0-aeba-08de5f3b65bd"
}
