@BankRUs.Api_HostAddress = https://localhost:8000

### Öppna konto

POST https://localhost:8000/api/accounts
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Doe",
  "socialSecurityNumber": "19900101-2013",
  "email": "jane@doe.com"
}

### Open Bank Account

POST https://localhost:8000/api/bank-accounts
Content-Type: application/json

{
  "userId": "3fda990b-c510-437e-02d3-08de5e6a1498"
}
