@BankRUs.Api_HostAddress = https://localhost:8000

### Öppna konto

POST https://localhost:8000/api/accounts
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Doe",
  "socialSecurityNumber": "19900101-2013",
  "email": "jane@doe.com"
}

### Open Bank Account

POST https://localhost:8000/api/bank-accounts
Content-Type: application/json

{
  "userId": "d11d286d-958a-4af4-e9b4-08de5e44902d"
}
